/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package talktalkchatty;

import com.sun.glass.events.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;
import javax.swing.text.Element;
import javax.swing.text.html.HTMLDocument;

/**
 *
 * @author JVAC
 */
public class chat extends javax.swing.JFrame {

    /**
     * Creates new form chat
     */
    private conexion co;
    private seguridad se;
    private String nombre;
    private String email;
    private String id;
    private String foto;
    DefaultListModel<String> modelo;//contiene los nombre de los usuarios
    DefaultListModel<String> modelo_id;//contiene los ids de los nombre de los usuarios

    public chat(conexion con, seguridad seg, String ids, String nom, String photo, String e) 
    {
        initComponents();
        co = con;
        co.asignarCH(this);
        se = seg;
        id = ids;
        nombre = nom;
        email = e;
        this.nomPerfil.setText(nombre);
        foto = photo;
        almacenamiento al = new almacenamiento();
        
        if(al.existeUsuarioLocal(email))
        {
        
        }
        else
        {
            al.crearNuevoUsuarioLocal(email, email, nombre, foto, id);
        }
        
        String ima = al.descomprimir(photo,email+"/archivo.temp",email+"/");
        //AQUI imagen conversacion
        Imagen imgUsu,imgPerfil;
        imgUsu = new Imagen(panelImgConversacion.getWidth(),panelImgConversacion.getHeight(),"logoTTC.png");        
        panelImgConversacion.add(imgUsu);
        panelImgConversacion.repaint();
        
        //AQUI imagen perfil usuario
        if(ima != "")
        {
           imgPerfil= new Imagen(panelImgConversacion.getWidth(),panelImgConversacion.getHeight(),ima,1);
        }
        else
        {
           imgPerfil = new Imagen(panelImgConversacion.getWidth(),panelImgConversacion.getHeight(),"logoTTC.png");        
        }
        imagenPerfil.add(imgPerfil);
        imagenPerfil.repaint();
        
        // Preparada para anyadir usuarios y conversaciones
        modelo = new DefaultListModel();
        modelo_id= new <String>DefaultListModel();
        this.CargarConversacion();
        String bienvenida = "<h1 align=\"center\">Bienvenid@ a TalkTalkChatty "+this.nombre+"</h1><br/><br/><p align=\"center\"><b>Para empezar a utilizar el chat agregue conversaciones con \"+\" o seleccione el usuario o grupo desde el panel izquierdo.</b></p>";
        this.pantalla.setText(bienvenida);
        this.lab_ConectUsu.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adjuntarFrame = new javax.swing.JFrame();
        adjuntarArchivo = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        botonAnyadir = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaConversaciones = new javax.swing.JList<>();
        Perfil = new javax.swing.JPanel();
        imagenPerfil = new javax.swing.JPanel();
        nomPerfil = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pantalla = new javax.swing.JEditorPane();
        botonEnviar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputTexto = new javax.swing.JEditorPane();
        lab_ConectUsu = new javax.swing.JLabel();
        nomConversacion = new javax.swing.JLabel();
        panelImgConversacion = new javax.swing.JPanel();
        botonEmoji = new javax.swing.JButton();
        botonAdjuntar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        env_imgagen = new javax.swing.JMenuItem();
        env_video = new javax.swing.JMenuItem();
        env_audio = new javax.swing.JMenuItem();
        env_documento = new javax.swing.JMenuItem();
        edit_perfil = new javax.swing.JMenuItem();
        new_grupo = new javax.swing.JMenuItem();
        del_grupo = new javax.swing.JMenuItem();
        chg_foto_grupo = new javax.swing.JMenuItem();

        javax.swing.GroupLayout adjuntarFrameLayout = new javax.swing.GroupLayout(adjuntarFrame.getContentPane());
        adjuntarFrame.getContentPane().setLayout(adjuntarFrameLayout);
        adjuntarFrameLayout.setHorizontalGroup(
            adjuntarFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(adjuntarFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(adjuntarFrameLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(adjuntarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        adjuntarFrameLayout.setVerticalGroup(
            adjuntarFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(adjuntarFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(adjuntarFrameLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(adjuntarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        botonAnyadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/talktalkchatty/plusIconMini.png"))); // NOI18N
        botonAnyadir.setMaximumSize(new java.awt.Dimension(35, 35));
        botonAnyadir.setMinimumSize(new java.awt.Dimension(35, 35));
        botonAnyadir.setPreferredSize(new java.awt.Dimension(35, 35));
        botonAnyadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAnyadirMouseClicked(evt);
            }
        });
        botonAnyadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnyadirActionPerformed(evt);
            }
        });

        botonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/talktalkchatty/trashIconMini.png"))); // NOI18N
        botonEliminar.setToolTipText("");
        botonEliminar.setPreferredSize(new java.awt.Dimension(35, 35));
        botonEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonEliminarMouseClicked(evt);
            }
        });
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        listaConversaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaConversacionesMouseClicked(evt);
            }
        });
        listaConversaciones.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaConversacionesValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(listaConversaciones);

        Perfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Perfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirPerfilPropio(evt);
            }
        });

        imagenPerfil.setBackground(new java.awt.Color(255, 255, 255));
        imagenPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imagenPerfil.setPreferredSize(new java.awt.Dimension(50, 50));
        imagenPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirPerfilPropio(evt);
            }
        });

        javax.swing.GroupLayout imagenPerfilLayout = new javax.swing.GroupLayout(imagenPerfil);
        imagenPerfil.setLayout(imagenPerfilLayout);
        imagenPerfilLayout.setHorizontalGroup(
            imagenPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        imagenPerfilLayout.setVerticalGroup(
            imagenPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        nomPerfil.setText("Nombre");
        nomPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nomPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirPerfilPropio(evt);
            }
        });

        javax.swing.GroupLayout PerfilLayout = new javax.swing.GroupLayout(Perfil);
        Perfil.setLayout(PerfilLayout);
        PerfilLayout.setHorizontalGroup(
            PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PerfilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagenPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomPerfil)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PerfilLayout.setVerticalGroup(
            PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PerfilLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PerfilLayout.createSequentialGroup()
                        .addComponent(imagenPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PerfilLayout.createSequentialGroup()
                        .addComponent(nomPerfil)
                        .addGap(22, 22, 22))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Perfil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(botonAnyadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonAnyadir, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(botonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pantalla.setEditable(false);
        pantalla.setContentType("text/html"); // NOI18N
        pantalla.setMaximumSize(new java.awt.Dimension(6, 6));
        pantalla.addHyperlinkListener(new javax.swing.event.HyperlinkListener() {
            public void hyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {
                pantallaHyperlinkUpdate(evt);
            }
        });
        jScrollPane2.setViewportView(pantalla);

        botonEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/talktalkchatty/sendIconMini.png"))); // NOI18N
        botonEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonEnviarMouseClicked(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        inputTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputTextoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(inputTexto);
        inputTexto.getAccessibleContext().setAccessibleName("cosaPrueba");

        lab_ConectUsu.setText("Última conexión: 18:09");

        nomConversacion.setText("Conversación");

        panelImgConversacion.setBackground(new java.awt.Color(255, 255, 255));
        panelImgConversacion.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout panelImgConversacionLayout = new javax.swing.GroupLayout(panelImgConversacion);
        panelImgConversacion.setLayout(panelImgConversacionLayout);
        panelImgConversacionLayout.setHorizontalGroup(
            panelImgConversacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        panelImgConversacionLayout.setVerticalGroup(
            panelImgConversacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        botonEmoji.setIcon(new javax.swing.ImageIcon(getClass().getResource("/talktalkchatty/emoji CS mini.png"))); // NOI18N
        botonEmoji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEmojiActionPerformed(evt);
            }
        });

        botonAdjuntar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/talktalkchatty/clipIconMini.png"))); // NOI18N
        botonAdjuntar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdjuntarActionPerformed(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(255, 102, 204));
        jMenuBar1.setBorder(null);

        menuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/talktalkchatty/menuIconMini.png"))); // NOI18N

        env_imgagen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_MASK));
        env_imgagen.setText("Enviar imagen");
        env_imgagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                env_imgagenActionPerformed(evt);
            }
        });
        menuArchivo.add(env_imgagen);

        env_video.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK));
        env_video.setText("Enviar vídeo");
        menuArchivo.add(env_video);

        env_audio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK));
        env_audio.setText("Enviar audio");
        menuArchivo.add(env_audio);

        env_documento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK));
        env_documento.setText("Enviar documento");
        menuArchivo.add(env_documento);

        edit_perfil.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        edit_perfil.setText("Editar perfil");
        edit_perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_perfilActionPerformed(evt);
            }
        });
        menuArchivo.add(edit_perfil);

        new_grupo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_MASK));
        new_grupo.setText("Nuevo grupo");
        new_grupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_grupoActionPerformed(evt);
            }
        });
        menuArchivo.add(new_grupo);

        del_grupo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK));
        del_grupo.setText("Borrar grupo");
        del_grupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_grupoActionPerformed(evt);
            }
        });
        menuArchivo.add(del_grupo);

        chg_foto_grupo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK));
        chg_foto_grupo.setText("Cambiar foto de grupo");
        chg_foto_grupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chg_foto_grupoActionPerformed(evt);
            }
        });
        menuArchivo.add(chg_foto_grupo);

        jMenuBar1.add(menuArchivo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(botonEmoji, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(panelImgConversacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomConversacion)
                            .addComponent(lab_ConectUsu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                        .addComponent(botonAdjuntar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(nomConversacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lab_ConectUsu))
                            .addComponent(panelImgConversacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonAdjuntar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonEnviar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(botonEmoji, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        botonEnviar.getAccessibleContext().setAccessibleDescription("botonEnviar");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEnviarMouseClicked
            String mensa = "<p align=\"left\" style=\"width:220px;\">"+this.inputTexto.getText()+"</p>";
            String mensa2 = "<p align=\"right\" style=\"width:180px;color:#8D77B9;\">"+this.inputTexto.getText()+"</p>";
            almacenamiento al = new almacenamiento();
            int indice = listaConversaciones.getSelectedIndex(); 
            al.addmensaje(email,this.modelo_id.get(indice).replaceAll("(\\r|\\n)",""), mensa);
            co.enviarmensaje(id,this.modelo_id.get(indice).replaceAll("(\\r|\\n)",""), mensa2);
            this.refrescarConversacion();
    }//GEN-LAST:event_botonEnviarMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        int indice = listaConversaciones.getSelectedIndex(); // empieza en 0
        System.out.println("eliminar conversacion");
        //Comprobamos que haya algo seleccionado
        if (indice >= 0) {
            String mensaje = "¿Estás seguro de eliminar esta conversación?";
            int resp = JOptionPane.showConfirmDialog(this,mensaje,"Eliminar",
                JOptionPane.YES_NO_OPTION);
                
            if (resp == 0) { 
                almacenamiento al = new almacenamiento();
                al.eliminarConversacion(email,this.modelo_id.get(indice));
                modelo.remove(indice);
                this.modelo_id.remove(indice);
                this.CargarConversacion();
            }
        }
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonAnyadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnyadirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAnyadirActionPerformed

    private void listaConversacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaConversacionesMouseClicked

    }//GEN-LAST:event_listaConversacionesMouseClicked

    private void botonEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEliminarMouseClicked
    
    }//GEN-LAST:event_botonEliminarMouseClicked

    private void botonEmojiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEmojiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEmojiActionPerformed

    private void botonAdjuntarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAdjuntarActionPerformed
        // TODO add your handling code here:
        int relVal = adjuntarArchivo.showOpenDialog(adjuntarFrame);
        if (relVal == JFileChooser.APPROVE_OPTION){
            //Ha subido un archivo
            File file = adjuntarArchivo.getSelectedFile();
            try {
              //Aqui habria que poner lo que hace con el archivo
            } catch (Exception ex) {
              System.out.println("problem accessing file"+file.getAbsolutePath());
            }
        } 
        else {
            //No ha subido nada
            System.out.println("File access cancelled by user.");
        }   
    }//GEN-LAST:event_botonAdjuntarActionPerformed

    private void abrirPerfilPropio(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirPerfilPropio
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(() -> {
            new Perfil(se,co,id,nombre,foto,email).setVisible(true);
            
        });
        this.setVisible(false);
    }//GEN-LAST:event_abrirPerfilPropio

    private void botonAnyadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAnyadirMouseClicked
            // TODO add your handling code here:
            String ids = JOptionPane.showInputDialog(this,"Agregue el id del usuario o correo(sin #):");
            if(ids != null)
            co.searchUser(ids, this);
    }//GEN-LAST:event_botonAnyadirMouseClicked

    private void inputTextoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputTextoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            String nombre = JOptionPane.showInputDialog(this,"Nombre del grupo a crear:");
        }
    }//GEN-LAST:event_inputTextoKeyPressed

    private void env_imgagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_env_imgagenActionPerformed
        // TODO add your handling code here:
        int relVal = adjuntarArchivo.showOpenDialog(adjuntarFrame);
        if (relVal == JFileChooser.APPROVE_OPTION) {
            //Ha subido un archivo
            File file = adjuntarArchivo.getSelectedFile();
            try{
                int i;
                String ext = file.getName().substring(file.getName().lastIndexOf(".") + 1);
                String[] extPermitidos = {"png","jpg"};
                
                for (i = 0; i < extPermitidos.length; i++) {
                    if(extPermitidos[i].equals(ext))break;
                }
                if(i<extPermitidos.length){
                    
                    String mensa = "<p align=\"left\" style=\"width:220px;\">"+file+"</p>";
                    String mensa2 = "<p align=\"right\" style=\"width:180px;color:#8D77B9;\">"+file+"</p>";
                    almacenamiento al = new almacenamiento();
                    int indice = listaConversaciones.getSelectedIndex(); 
                    al.addmensaje(email,this.modelo_id.get(indice).replaceAll("(\\r|\\n)",""), mensa);
                    co.enviarmensaje(id,this.modelo_id.get(indice).replaceAll("(\\r|\\n)",""), mensa2);
                    this.refrescarConversacion();
                }else{
                    throw new Exception(". Formato no permitido");
                }
            } catch (Exception ex) {
              System.out.println("problem accessing file"+file.getAbsolutePath());
            }
        } 
        else {
            //No ha subido nada
            System.out.println("File access cancelled by user.");
        }   
    }//GEN-LAST:event_env_imgagenActionPerformed

    private void edit_perfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_perfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_perfilActionPerformed

    private void new_grupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_grupoActionPerformed
       String ids = JOptionPane.showInputDialog(this,"Agregue el id del usuario o correo(sin #):");
    }//GEN-LAST:event_new_grupoActionPerformed

    private void chg_foto_grupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chg_foto_grupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chg_foto_grupoActionPerformed

    private void listaConversacionesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaConversacionesValueChanged
        // TODO add your handling code here:
        //aqui cargamos la conversacion
        //la carga sera simple los mensajes del usuario seran puesto con p y b en la alineacion derecha, la del usuario a la izquierda con p y color azul clarito
        String valor = listaConversaciones.getSelectedValue();
        int indice = listaConversaciones.getSelectedIndex(); // empieza en 0
        nomConversacion.setText(valor);
        almacenamiento al = new almacenamiento();
        String [] conversa = al.obtenerConversacion(email,this.modelo_id.get(indice));
        System.out.println("Cambiamos a la conversacion con indice -> "+indice+" con id ->"+this.modelo_id.get(indice));
        String mensaje = "";
        if(conversa != null)
        {
            if(conversa.length == 0)
            {
                mensaje = "<h3 align=\"center\">Aun no ha empezado la conversacion con este usuario o grupo, envie un mensaje para empezar la conversacion</h3>";
            }
            else
            {
                for(String mensa:conversa)
                {
                    mensaje=mensaje+mensa;
                }
            }
            pantalla.setText(mensaje);
        }
    }//GEN-LAST:event_listaConversacionesValueChanged

    private void del_grupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_grupoActionPerformed
        // TODO add your handling code here:
       /* String grupoAEliminar = JOptionPane.showInputDialog("Selecciona la conversaicón a eliminar").toString();
        for(int i=0; i< listaConversaciones.getComponentCount(); i++)
        {
            if(listaConversaciones.)
        }
        int indice = listaConversaciones.getSelectedIndex(); // empieza en 0
        System.out.println("eliminar conversacion");
        //Comprobamos que haya algo seleccionado
        if (indice >= 0) {
            String mensaje = "¿Estás seguro de eliminar esta conversación?";
            int resp = JOptionPane.showConfirmDialog(this,mensaje,"Eliminar",
                JOptionPane.YES_NO_OPTION);
                
            if (resp == 0) { 
                almacenamiento al = new almacenamiento();
                al.eliminarConversacion(email,this.modelo_id.get(indice));
                modelo.remove(indice);
                this.modelo_id.remove(indice);
                this.CargarConversacion();
            }
        }*/
          
    }//GEN-LAST:event_del_grupoActionPerformed

    public void contestSearchUser(String ids,String nombre,String confirmacion, String foto)
    {
        if(confirmacion.contains("true"))
        {
            if(!this.modelo.contains(nombre))
            {
                //aqui agregamos el contacto o grupo al listado
                this.modelo.addElement(nombre);
                this.modelo_id.addElement(ids);
                almacenamiento al = new almacenamiento();
                al.crearConversacion(this.email, ids, nombre, foto);
                if(!(modelo.size() > 1))
                {
                    listaConversaciones.setModel(modelo);
                }
                //creamos su apartado de chat
            }
            else
            {
                JOptionPane.showMessageDialog(this,"El usuario o grupo "+nombre+" ya esta en tu lista de chat activos.");
            }
        }
        else
        {
            //mostramos mensaje de error
            JOptionPane.showMessageDialog(this,"El usuario o grupo  -> "+ids+" no existe.");
        }
    }
    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Perfil;
    private javax.swing.JFileChooser adjuntarArchivo;
    private javax.swing.JFrame adjuntarFrame;
    private javax.swing.JButton botonAdjuntar;
    private javax.swing.JButton botonAnyadir;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonEmoji;
    private javax.swing.JButton botonEnviar;
    private javax.swing.JMenuItem chg_foto_grupo;
    private javax.swing.JMenuItem del_grupo;
    private javax.swing.JMenuItem edit_perfil;
    private javax.swing.JMenuItem env_audio;
    private javax.swing.JMenuItem env_documento;
    private javax.swing.JMenuItem env_imgagen;
    private javax.swing.JMenuItem env_video;
    private javax.swing.JPanel imagenPerfil;
    private javax.swing.JEditorPane inputTexto;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lab_ConectUsu;
    private javax.swing.JList<String> listaConversaciones;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuItem new_grupo;
    private javax.swing.JLabel nomConversacion;
    private javax.swing.JLabel nomPerfil;
    private javax.swing.JPanel panelImgConversacion;
    private javax.swing.JEditorPane pantalla;
    // End of variables declaration//GEN-END:variables
    
    
    
    private void CargarConversacion() {
        //esto se ejecuta en el inicio 
        //carga todas las conversaciones y sus ids
        almacenamiento al = new almacenamiento();
        String conver[] = al.obtenerConversaciones(email);
        if(conver.length > 0)
        {
            for(String a:conver)   
            {
                modelo.addElement(al.obtenerNombre(email,a));
                modelo_id.addElement(a);
            }
            listaConversaciones.setModel(modelo);
        }
    }
    private int SacarNumeroMiembrosGrupo(int indice, String grupo) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    private void CargarListaConversaciones() {
        listaConversaciones.setModel(modelo);
    }
    
    public boolean refrescarConversacion()
    {
        int indice = listaConversaciones.getSelectedIndex();
        almacenamiento al = new almacenamiento();
        String [] conversa = al.obtenerConversacion(email,this.modelo_id.get(indice));
        String mensaje = "";
        if(conversa != null)
        {
            if(conversa.length == 0)
            {
                mensaje = "<h3 align=\"center\">Aun no ha empezado la conversacion con este usuario o grupo, envie un mensaje para empezar la conversacion</h3>";
            }
            else
            {
                for(String mensa:conversa)
                {
                    mensaje=mensaje+mensa;
                }
            }
            pantalla.setText(mensaje);
        }
        return true;
    }
    
    public void sentMen(String origen, String men)
    {
        //vamos a comprobar si existe
        //si no existe lo agregaremos al principio
        boolean existe = false;
        int indice = listaConversaciones.getSelectedIndex();
        for(int a=0;a < this.modelo_id.size();a++)
        {
            if(this.modelo_id.get(a).compareToIgnoreCase(origen) == 0)
            {
                existe = true;
            }
        }
        
        if(existe)
        {
           almacenamiento al = new almacenamiento();
           al.addmensaje(email, origen, men.split("#codes@")[0]);
           System.out.println("Se agrega mensaje de origen -> "+origen);   
           this.refrescarConversacion();
        }
        else
        {
           co.searchUser(origen, this);
           almacenamiento al = new almacenamiento();
           al.addmensajenuevo(email, origen, men.split("#codes@")[0]);
        }
    }
}
